CREATE TABLE teams(
  id INT(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(255) NOT NULL,
  rating VARCHAR(255) NOT NULL ,
  deviation VARCHAR(255) NOT NULL ,
  volatility VARCHAR(255) NOT NULL
);



